spring.application.name=todos

spring.datasource.url=jdbc:mysql://localhost:13306/tododb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


springdoc.swagger-ui.path=/docs

spring.jwt.secret=791a50f3279f707afdacbc606632eb0b2f2a762b6a4a271073fe081c5e1ffc71
spring.jwt.expiration=900000